export const allCards = [
  {
    id: 1,
    topic: "Спорт",
    title: "Сходить в зал",
    description: "День ног",
    status: "done",
    theme: "_blue",
    date: "30.10.23",
  },
  {
    id: 2,
    topic: "Здоровье",
    title: "Сходить в баню",
    description: "Найти баню",
    status: "to-do",
    theme: "_green",
    date: "06.02.25",
  },
  {
    id: 3,
    topic: "Учеба",
    title: "Найти репетитора по гитаре",
    description: "Выделить время",
    status: "no-status",
    theme: "_orange",
    date: "30.10.23",
  },
  {
    id: 4,
    topic: "Спорт",
    title: "Найти другой спорт зал",
    description: "Выделить время",
    status: "no-status",
    theme: "_blue",
    date: "30.10.23",
  },
  {
    id: 5,
    topic: "Учеба",
    title: "Сделать ДЗ",
    description: "ознакомиться с ТЗ",
    status: "to-do",
    theme: "_orange",
    date: "30.10.23",
  },
  {
    id: 6,
    topic: "Проект",
    title: "Создать сайт-визитку",
    description: "Пригласительные",
    status: "testing",
    theme: "_pink",
    date: "30.10.23",
  },
  {
    id: 7,
    topic: "Учеба",
    title: "Сдать курсовую по JS",
    description: "Доделать курсовую",
    status: "done",
    theme: "_orange",
    date: "30.10.23",
  },
  {
    id: 8,
    topic: "Отдых",
    title: "Прочитать книгу",
    description: "Стивен Кинг",
    status: "in-progress",
    theme: "_purple",
    date: "30.10.23",
  },
  {
    id: 9,
    topic: "Путешествия",
    title: "Хайкинг в Гонконге",
    description: "Сделано",
    status: "done",
    theme: "_yellow",
    date: "30.10.23",
  },
];

export const columnsData = [
  { title: "Без статуса", status: "no-status", theme: "_orange" },
  { title: "Нужно сделать", status: "to-do", theme: "_blue" },
  { title: "В работе", status: "in-progress", theme: "_green" },
  { title: "Тестирование", status: "testing", theme: "_purple" },
  { title: "Готово", status: "done", theme: "_darkGreen" },
];
